project:
  type: website
  pre-render:
    - quarto render book        # build the book first
  render:
    - "*.qmd"
    - "dashboards/*.qmd"
    - "!book/*.qmd"
    - "!book/**/*.qmd"          # don't render book sources as pages

website:
  title: "ACL Rehabilitation Hub"
  favicon: images/csi-logo-medal-only.png
  navbar:
    logo: images/csi-pacific-logo-reverse-300x136.png
    logo-alt: "Take me to the homepage"
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "ACL Guide"
        href: guide.qmd
      - text: "Dashboards"
        menu:
          - text: "Force Plates"
            href: dashboards/dashboard1.qmd
          - text: "Shiny App"
            href: app-inline.qmd
      - text: "Progress Reports"
        menu:
          - text: "Phase 1"
            href: checklists/phase1_checklist.qmd
          - text: "Return to Jumping"
            href: checklists/return_to_jump_checklist.qmd            
          - text: "Return to Running"
            href: checklists/return_to_run_checklist.qmd
    right:
      - icon: github
        href: https://github.com/AKates717/CSI-Pacific-RTP
      - icon: globe
        href: https://csipacific.ca
  page-footer: 
    left: |
       ![](/images/csi-logo-medal-only.png){width="10%" style="position: relative; top: 15px;"}
    center: "We gratefully and respectfully acknowledge that our workplaces exist on the traditional, ancestral and unceded Lands of the xwməθkwəy̓əm (Musqueam), Skwxwú7mesh (Squamish), L̓il̓wat7úl (Lil’wat), Esquimalt and Songhees Nations of the Coast Salish peoples."
    right: This website is built with [{{< iconify fa6-brands:r-project >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
    background: black

format:
  html:
    theme: default
    css: 
      - styles.css
    toc: true
    page-layout: full
    link-external-newwindow: true
    
execute:
  echo: false
  warning: false
  message: false
    
# post-render:
#   - cp -r book/_book _site/book
